### ISSUE TITLE
Set a max file size to scan

### ISSUE THREAD

**Issue by aruethe2** [Swarthmore/filescan#2]
To prevent timeouts

**Comment by devnoot** [comment]
What would be a feasible max file size for a PDF? I'm thinking 10Mb would suffice

**Comment by aruethe2** [comment]
10MB is probably too small.  We currently have >5400 unique PDF files in Moodle greater than 10MB.  Only 97 are greater than 100MB and 25 greater than 200MB.  Maybe 100MB?
