### ISSUE TITLE
Check into how to install Guzzle

### ISSUE THREAD

**Issue by aruethe2** [Swarthmore/filescan#3]
Not sure how best to require Guzzle for all systems.  Currently just include files in the vendor directory.

**Comment by aruethe2** [comment]
@mackensen suggests moving to a separate folder in the plugin with a note stating the version of Guzzle used.

**Comment by devnoot** [comment]
It's not a bug but this should be fixed before pushing an official release

**Comment by aruethe2** [comment]
Can we replace Guzzle with a Moodlelib function? 

I found a download_file_content function in [/lib/filelib.php](https://github.com/moodle/moodle/blob/master/lib/filelib.php)

> Fetches content of file from Internet (using proxy if defined). Uses cURL extension if present.

Further down in filelib.php, there are is a curl class with examples of downloading multiple files in parallel.  Search for "Download multiple files in parallel"

**Comment by devnoot** [comment]
please see #49

**Comment by devnoot** [comment]
fixed in pr #57
