### ISSUE TITLE
Access archetype permissions conflict with clonepermissionsfrom setting

### ISSUE THREAD

**Issue by kwiliarty** [Swarthmore/filescan#39]
In `db/access.php` the `block_filescan:scan` permission is defined this way:

```
  'block/filescan:scan' => array(
    'riskbitmask' => RISK_PERSONAL,
    'captype' => 'read',
    'contextlevel' => CONTEXT_COURSE,
    'archetypes' => array(
      'guest'           => CAP_PREVENT,
      'student'         => CAP_PREVENT,
      'teacher'         => CAP_PREVENT,
      'coursecreator'   => CAP_ALLOW,
      'editingteacher'  => CAP_ALLOW,
      'manager'         => CAP_ALLOW
    ),
    'clonepermissionsfrom' => 'moodle/course:update',
  ),
```

The settings in `archetypes` suggest that guests, students and teachers should be set to `CAP_PREVENT` for this capability, but if that is the design then it is not happening as planned because the permissions are being cloned from `moodle/course:update` where the roles in question typically have different or unset permissions. On a brand new installation right after installing `block_filescan` I find that `block_filescan:scan` is unset for guests and students and set to `CAP_ALLOW` for teachers.

<img width="355" alt="unexpected-settings" src="https://user-images.githubusercontent.com/407636/51397943-56ba7e00-1b10-11e9-9dbe-374c3bc0e704.png">

The `archetypes` element and the `clonepermissionsfrom` element seem to be in conflict. I'm not sure which permissions you want, but I think it would be good to resolve the conflict.

**Comment by devnoot** [comment]
This should be resolved in pr #57
