### ISSUE TITLE
Error when installing with Postgres

### ISSUE THREAD

**Issue by kwiliarty** [Swarthmore/filescan#40]
I haven't seen anything like this with MySQL/MariaDB but when I try to install a PostgresQL database I'm getting this error:

> block_filescan
> 
> DDL sql execution error
> 
> More information about this error
> 
> It is usually not possible to recover from errors triggered during installation, you may need to create a new database or use a different database prefix if you want to retry the installation.
> Debug info: ERROR: column "timechecked" is of type timestamp without time zone but default expression is of type integer
> HINT: You will need to rewrite or cast the expression.
> BEGIN ISOLATION LEVEL SERIALIZABLE;
> CREATE TABLE m_block_filescan_files (
> id BIGSERIAL,
> contenthash VARCHAR(40) NOT NULL DEFAULT '',
> checked SMALLINT NOT NULL,
> pagecount BIGINT,
> status VARCHAR(20),
> statuscode BIGINT DEFAULT 0,
> hastext SMALLINT,
> hastitle SMALLINT,
> hasoutline SMALLINT,
> haslanguage SMALLINT,
> timechecked TIMESTAMP NOT NULL DEFAULT 0,
> courseinfo TEXT,
> CONSTRAINT m_blocfilefile_id_pk PRIMARY KEY (id)
> )
> ;
> COMMENT ON TABLE m_block_filescan_files IS 'Filescan results'
> ; COMMIT
> Error code: ddlexecuteerror
> Stack trace:
> 
>     line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
>     line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
>     line 676 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
>     line 77 of /lib/ddl/database_manager.php: call to pgsql_native_moodle_database->change_database_structure()
>     line 425 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
>     line 370 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
>     line 969 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
>     line 520 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
>     line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
>     line 694 of /admin/index.php: call to upgrade_noncore()

**Comment by devnoot** [comment]
This should be fixed (See issue #44)
