### ISSUE TITLE
Problem installing on PostgreSQL?

### ISSUE THREAD

**Issue by jproctor** [Swarthmore/filescan#44]
Running Moodle 3.6.4 and PostgreSQL 9.6.13 on Debian 9.9, when I put the files into blocks/ and click "Upgrade Moodle database now" in the web UI, I get an error that blocks installation:

> DDL sql execution error
>
> [More information about this error](http://docs.moodle.org/36/en/error/moodle/ddlexecuteerror)

> **Debug info:** ERROR: column "timechecked" is of type timestamp without time zone but default expression is of type integer
HINT: You will need to rewrite or cast the expression.
BEGIN ISOLATION LEVEL SERIALIZABLE;
CREATE TABLE mdl_block_filescan_files (
id BIGSERIAL,
contenthash VARCHAR(40) NOT NULL DEFAULT '',
checked SMALLINT NOT NULL,
pagecount BIGINT,
status VARCHAR(20),
statuscode BIGINT DEFAULT 0,
hastext SMALLINT,
hastitle SMALLINT,
hasoutline SMALLINT,
haslanguage SMALLINT,
timechecked TIMESTAMP NOT NULL DEFAULT 0,
courseinfo TEXT,
CONSTRAINT mdl_blocfilefile_id_pk PRIMARY KEY (id)
)
;
COMMENT ON TABLE mdl_block_filescan_files IS 'Filescan results'
; COMMIT
Error code: ddlexecuteerror

> **Stack trace:**
> - line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
> - line 248 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
> - line 676 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
> - line 77 of /lib/ddl/database_manager.php: call to pgsql_native_moodle_database->change_database_structure()
> - line 425 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
> - line 370 of /lib/ddl/database_manager.php: call to database_manager->install_from_xmldb_structure()
> - line 969 of /lib/upgradelib.php: call to database_manager->install_from_xmldb_file()
> - line 520 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
> - line 1852 of /lib/upgradelib.php: call to upgrade_plugins()
> - line 694 of /admin/index.php: call to upgrade_noncore()

Best guess based on the error message is that PSQL won’t take integer `0` as its zero-value timestamp, so now I’m going to poke around and see if I can find an alternative.

**Comment by jproctor** [comment]
Update 1: I don’t think there’s a db-neutral way to say timestamp 0. (Ugh.)

I got it to install by allowing that column to be `NULL` and removing the default, but I'm guessing you have code that's checking for `0` instead of `NULL`, so that may blow up. (Another update coming once we’ve tried it.)

**Comment by jproctor** [comment]
Update 2: we added the block to a new empty course, added files to the course, and it found the files fairly quickly but after 20 minutes has not (apparently) scanned them: they're all still question marks.

So possibly it’s blowing up as I predicted above, possibly I gave it the wrong URL for filescanning because that’s not actually documented anywhere and I had to guess http://localhost:8080/file (based on a copy of filescan-server separate from the one actually running on the moodle server), possibly something else. Happy to help debug, but don’t know where to look next.

**Comment by aruethe2** [comment]
@jproctor - the url for the server is just the base url: http://localhost:8080.   Thanks for mentioning that it is missing from the docs.  

I'd suggest looking the scheduled task log for the filescan task to see what error messages might have showed up.  Or you could add a new file and then run the task manually and look for any errors.

Schedule tasks: Site admin --> Server --> Scheduled tasks --> Filescan task.  

I'll check to see the effect of null versus 0 in the database.

**Comment by jproctor** [comment]
Trying to run now:

> Execute scheduled task: Filescan task (block_filescan\task\scan_files)
Filescan cron script is running
Looking up files to scan
... used 6 dbqueries
... used 0.031959056854248 seconds
Scheduled task failed: Filescan task (block_filescan\task\scan_files),Error reading from database

Basically the same gets logged from the scheduled task.

I tried executing the query from classes/task/scan_files.php and got three psql complaints: it wants single quotes on literal strings, the `checked` column is integer so can’t be compared to boolean, and `ORDER BY f.id` requires that `f.id` be one of the things in the `SELECT` list.

After making those changes I get a list of content hashes on a manual query. I’ll try changing in the PHP in a bit.

**Comment by aruethe2** [comment]
OK, great.  That is helpful info.  I am very MySQL/MariaDB-centric so it is good to know the info about Postgres.  

I did look at the code for the timechecked field and don't see anywhere that 0 versus null would make a difference.

**Comment by jproctor** [comment]
Me too, but I inherited this one mission-critical psql system; every so often I have to pretend to be bilingual. I just keep trying things and Googling for Stack Exchange results until it stops giving me syntax errors. :)

BTW, we’re not thinking about having this in production until probably late fall. I can put together a patch file or a PR for you (whichever you prefer), but I’m in no hurry to get it officially integrated. Also Hack/Doc might wrap up today before I’m actually done.

**Comment by jproctor** [comment]
Got past the first query, then it barfed on the second:

> ERROR:  column "f.pathnamehash" must appear in the GROUP BY clause or be used in an aggregate function

I added it to the `GROUP BY` and it seems to work. It scanned those recent docs, anyway, and will presumably start chugging along on the older ones.

I’ll package the changes up for you to run against MySQL and make sure it doesn’t break the more common usage.
