### ISSUE TITLE
Add index on contenthash in filescan_files table

### ISSUE THREAD

**Issue by aruethe2** [Swarthmore/filescan#47]
Greatly speeds up database queries used to generate content for the block.

Need to update the  `db/install.xml` file using `<INDEX>`
https://docs.moodle.org/dev/XMLDB_defining_an_XML_structure#The_INDEX_element
and `db/upgrade.php` file with `$dbman->add_index` https://docs.moodle.org/dev/Data_definition_API#Handling_indexes

**Comment by devnoot** [comment]
please see #51

**Comment by devnoot** [comment]
fixed in pr #57
