### ISSUE TITLE
Enhancement: Allow detail view to be exported as spreadsheet

### ISSUE THREAD

**Issue by CorrineS** [Swarthmore/filescan#65]
We could use this to mark which items should be exported for remediation, which are okay, and which have accessible online alternatives

For some reason I'm not able to add a label to this - should be an **enhancement**

**Comment by CorrineS** [comment]
Didn't realize there was another issue requesting a similar thing - #21 These should be combined

**Comment by aruethe2** [comment]
Duplicate of #21
